CREATE TABLE IF NOT EXISTS users (
	id INT NOT NULL,
	username VARCHAR (64) NOT NULL PRIMARY KEY,
	password VARCHAR (500) NOT NULL,
	enabled BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS authorities (
	id INT NOT NULL,
	username VARCHAR (64) NOT NULL PRIMARY KEY,
	authority VARCHAR (64) NOT NULL,
	FOREIGN KEY fk_authority_users (username) REFERENCES users(username)
);  

CREATE TABLE IF NOT EXISTS bicycles(
   id INT NOT NULL PRIMARY KEY,
   bikename VARCHAR(200) NOT NULL,
   brandid VARCHAR(2) NOT NULL,
   brand VARCHAR(10) NOT NULL,
   size VARCHAR(10) NOT NULL,
   color VARCHAR(20) NOT NULL,
   value INT NOT NULL
);

CREATE TABLE IF NOT EXISTS shops(
   id INT NOT NULL PRIMARY KEY,
   shopid VARCHAR(4) NOT NULL,
   name VARCHAR(50) NOT NULL 
);

CREATE TABLE IF NOT EXISTS favorite(
   id INT NOT NULL,
   username VARCHAR (64) NOT NULL PRIMARY KEY,
   bikename VARCHAR(200) NOT NULL
);